//
// ????? JavaTM Architecture for XML Binding (JAXB) ???? v2.2.8-b130911.1802 ???
// ??? <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// ?????????, ??????????????
// ????: 2018.03.12 ?? 11:42:22 PM CET 
//


package Ar421;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>COLLECTABLE-ELEMENT--SUBTYPES-ENUM? Java ??
 * 
 * <p>????????????????????
 * <p>
 * <pre>
 * &lt;simpleType name="COLLECTABLE-ELEMENT--SUBTYPES-ENUM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AR-ELEMENT"/>
 *     &lt;enumeration value="AR-PACKAGE"/>
 *     &lt;enumeration value="ABSTRACT-CAN-CLUSTER"/>
 *     &lt;enumeration value="ACL-OBJECT-SET"/>
 *     &lt;enumeration value="ACL-OPERATION"/>
 *     &lt;enumeration value="ACL-PERMISSION"/>
 *     &lt;enumeration value="ACL-ROLE"/>
 *     &lt;enumeration value="ALIAS-NAME-SET"/>
 *     &lt;enumeration value="APPLICATION-ARRAY-DATA-TYPE"/>
 *     &lt;enumeration value="APPLICATION-COMPOSITE-DATA-TYPE"/>
 *     &lt;enumeration value="APPLICATION-DATA-TYPE"/>
 *     &lt;enumeration value="APPLICATION-PRIMITIVE-DATA-TYPE"/>
 *     &lt;enumeration value="APPLICATION-RECORD-DATA-TYPE"/>
 *     &lt;enumeration value="APPLICATION-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="ATOMIC-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="AUTOSAR-DATA-TYPE"/>
 *     &lt;enumeration value="BASE-TYPE"/>
 *     &lt;enumeration value="BLUEPRINT-MAPPING-SET"/>
 *     &lt;enumeration value="BSW-IMPLEMENTATION"/>
 *     &lt;enumeration value="BSW-MODULE-DESCRIPTION"/>
 *     &lt;enumeration value="BSW-MODULE-ENTRY"/>
 *     &lt;enumeration value="BSW-MODULE-TIMING"/>
 *     &lt;enumeration value="BUILD-ACTION-MANIFEST"/>
 *     &lt;enumeration value="CALIBRATION-PARAMETER-VALUE-SET"/>
 *     &lt;enumeration value="CAN-CLUSTER"/>
 *     &lt;enumeration value="CAN-FRAME"/>
 *     &lt;enumeration value="CAN-TP-CONFIG"/>
 *     &lt;enumeration value="CLIENT-ID-DEFINITION-SET"/>
 *     &lt;enumeration value="CLIENT-SERVER-INTERFACE"/>
 *     &lt;enumeration value="COLLECTABLE-ELEMENT"/>
 *     &lt;enumeration value="COLLECTION"/>
 *     &lt;enumeration value="COMMUNICATION-CLUSTER"/>
 *     &lt;enumeration value="COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="COMPOSITION-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="COMPU-METHOD"/>
 *     &lt;enumeration value="CONSISTENCY-NEEDS-BLUEPRINT-SET"/>
 *     &lt;enumeration value="CONSTANT-SPECIFICATION"/>
 *     &lt;enumeration value="CONSTANT-SPECIFICATION-MAPPING-SET"/>
 *     &lt;enumeration value="CONTAINER-I-PDU"/>
 *     &lt;enumeration value="COUPLING-ELEMENT"/>
 *     &lt;enumeration value="DATA-CONSTR"/>
 *     &lt;enumeration value="DATA-INTERFACE"/>
 *     &lt;enumeration value="DATA-TRANSFORMATION-SET"/>
 *     &lt;enumeration value="DATA-TYPE-MAPPING-SET"/>
 *     &lt;enumeration value="DCM-I-PDU"/>
 *     &lt;enumeration value="DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-ACCESS-PERMISSION"/>
 *     &lt;enumeration value="DIAGNOSTIC-AGING"/>
 *     &lt;enumeration value="DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-COM-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-COM-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-COMMON-ELEMENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONDITION"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONDITION-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONNECTION"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTRIBUTION-SET"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTROL-DTC-SETTING"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-CUSTOM-SERVICE-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-IDENTIFIER-SET"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-TRANSFER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-TRANSFER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ECU-RESET"/>
 *     &lt;enumeration value="DIAGNOSTIC-ECU-RESET-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ENABLE-CONDITION"/>
 *     &lt;enumeration value="DIAGNOSTIC-ENABLE-CONDITION-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EXTENDED-DATA-RECORD"/>
 *     &lt;enumeration value="DIAGNOSTIC-FREEZE-FRAME"/>
 *     &lt;enumeration value="DIAGNOSTIC-IO-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-INDICATOR"/>
 *     &lt;enumeration value="DIAGNOSTIC-IO-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION-MIRROR"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-OPERATION-CYCLE"/>
 *     &lt;enumeration value="DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DTC-INFORMATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-DOWNLOAD"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-FILE-TRANSFER"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-UPLOAD"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-UPLOAD-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-RESPONSE-ON-EVENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-ACCESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-ACCESS-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-LEVEL"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-DATA-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-INSTANCE"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-SW-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-TABLE"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-STORAGE-CONDITION"/>
 *     &lt;enumeration value="DIAGNOSTIC-STORAGE-CONDITION-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-SW-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-TRANSFER-EXIT"/>
 *     &lt;enumeration value="DIAGNOSTIC-TRANSFER-EXIT-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-J-1939"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-OBD"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-PROPS"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-UDS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS"/>
 *     &lt;enumeration value="DOCUMENTATION"/>
 *     &lt;enumeration value="ECU-ABSTRACTION-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="ECU-INSTANCE"/>
 *     &lt;enumeration value="ECU-TIMING"/>
 *     &lt;enumeration value="ECUC-DEFINITION-COLLECTION"/>
 *     &lt;enumeration value="ECUC-DESTINATION-URI-DEF-SET"/>
 *     &lt;enumeration value="ECUC-MODULE-CONFIGURATION-VALUES"/>
 *     &lt;enumeration value="ECUC-MODULE-DEF"/>
 *     &lt;enumeration value="ECUC-VALUE-COLLECTION"/>
 *     &lt;enumeration value="END-TO-END-PROTECTION-SET"/>
 *     &lt;enumeration value="ETHERNET-CLUSTER"/>
 *     &lt;enumeration value="ETHERNET-FRAME"/>
 *     &lt;enumeration value="EVALUATED-VARIANT-SET"/>
 *     &lt;enumeration value="FM-FEATURE"/>
 *     &lt;enumeration value="FM-FEATURE-MAP"/>
 *     &lt;enumeration value="FM-FEATURE-MODEL"/>
 *     &lt;enumeration value="FM-FEATURE-SELECTION-SET"/>
 *     &lt;enumeration value="FIBEX-ELEMENT"/>
 *     &lt;enumeration value="FLAT-MAP"/>
 *     &lt;enumeration value="FLEXRAY-AR-TP-CONFIG"/>
 *     &lt;enumeration value="FLEXRAY-CLUSTER"/>
 *     &lt;enumeration value="FLEXRAY-FRAME"/>
 *     &lt;enumeration value="FLEXRAY-TP-CONFIG"/>
 *     &lt;enumeration value="FRAME"/>
 *     &lt;enumeration value="GATEWAY"/>
 *     &lt;enumeration value="GENERAL-PURPOSE-I-PDU"/>
 *     &lt;enumeration value="GENERAL-PURPOSE-PDU"/>
 *     &lt;enumeration value="GENERIC-ETHERNET-FRAME"/>
 *     &lt;enumeration value="GLOBAL-TIME-DOMAIN"/>
 *     &lt;enumeration value="HW-CATEGORY"/>
 *     &lt;enumeration value="HW-ELEMENT"/>
 *     &lt;enumeration value="HW-TYPE"/>
 *     &lt;enumeration value="I-PDU"/>
 *     &lt;enumeration value="I-SIGNAL"/>
 *     &lt;enumeration value="I-SIGNAL-GROUP"/>
 *     &lt;enumeration value="I-SIGNAL-I-PDU"/>
 *     &lt;enumeration value="I-SIGNAL-I-PDU-GROUP"/>
 *     &lt;enumeration value="IEEE-1722-TP-ETHERNET-FRAME"/>
 *     &lt;enumeration value="IMPLEMENTATION"/>
 *     &lt;enumeration value="IMPLEMENTATION-DATA-TYPE"/>
 *     &lt;enumeration value="INTERPOLATION-ROUTINE-MAPPING-SET"/>
 *     &lt;enumeration value="J-1939-CLUSTER"/>
 *     &lt;enumeration value="J-1939-DCM-I-PDU"/>
 *     &lt;enumeration value="J-1939-TP-CONFIG"/>
 *     &lt;enumeration value="KEYWORD-SET"/>
 *     &lt;enumeration value="LIFE-CYCLE-INFO-SET"/>
 *     &lt;enumeration value="LIFE-CYCLE-STATE-DEFINITION-GROUP"/>
 *     &lt;enumeration value="LIN-CLUSTER"/>
 *     &lt;enumeration value="LIN-EVENT-TRIGGERED-FRAME"/>
 *     &lt;enumeration value="LIN-FRAME"/>
 *     &lt;enumeration value="LIN-SPORADIC-FRAME"/>
 *     &lt;enumeration value="LIN-TP-CONFIG"/>
 *     &lt;enumeration value="LIN-UNCONDITIONAL-FRAME"/>
 *     &lt;enumeration value="MC-FUNCTION"/>
 *     &lt;enumeration value="MODE-DECLARATION-GROUP"/>
 *     &lt;enumeration value="MODE-DECLARATION-MAPPING-SET"/>
 *     &lt;enumeration value="MODE-SWITCH-INTERFACE"/>
 *     &lt;enumeration value="MULTIPLEXED-I-PDU"/>
 *     &lt;enumeration value="N-PDU"/>
 *     &lt;enumeration value="NM-CONFIG"/>
 *     &lt;enumeration value="NM-PDU"/>
 *     &lt;enumeration value="NV-BLOCK-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="NV-DATA-INTERFACE"/>
 *     &lt;enumeration value="PACKAGEABLE-ELEMENT"/>
 *     &lt;enumeration value="PARAMETER-INTERFACE"/>
 *     &lt;enumeration value="PARAMETER-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="PDU"/>
 *     &lt;enumeration value="PDUR-I-PDU-GROUP"/>
 *     &lt;enumeration value="PHYSICAL-DIMENSION"/>
 *     &lt;enumeration value="PHYSICAL-DIMENSION-MAPPING-SET"/>
 *     &lt;enumeration value="PORT-INTERFACE"/>
 *     &lt;enumeration value="PORT-INTERFACE-MAPPING-SET"/>
 *     &lt;enumeration value="PORT-PROTOTYPE-BLUEPRINT"/>
 *     &lt;enumeration value="POST-BUILD-VARIANT-CRITERION"/>
 *     &lt;enumeration value="POST-BUILD-VARIANT-CRITERION-VALUE-SET"/>
 *     &lt;enumeration value="PREDEFINED-VARIANT"/>
 *     &lt;enumeration value="RAPID-PROTOTYPING-SCENARIO"/>
 *     &lt;enumeration value="SECURED-I-PDU"/>
 *     &lt;enumeration value="SENDER-RECEIVER-INTERFACE"/>
 *     &lt;enumeration value="SENSOR-ACTUATOR-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="SERIALIZATION-TECHNOLOGY"/>
 *     &lt;enumeration value="SERVICE-PROXY-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="SERVICE-SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="SO-AD-ROUTING-GROUP"/>
 *     &lt;enumeration value="SW-ADDR-METHOD"/>
 *     &lt;enumeration value="SW-AXIS-TYPE"/>
 *     &lt;enumeration value="SW-BASE-TYPE"/>
 *     &lt;enumeration value="SW-COMPONENT-TYPE"/>
 *     &lt;enumeration value="SW-RECORD-LAYOUT"/>
 *     &lt;enumeration value="SW-SYSTEMCONST"/>
 *     &lt;enumeration value="SW-SYSTEMCONSTANT-VALUE-SET"/>
 *     &lt;enumeration value="SWC-BSW-MAPPING"/>
 *     &lt;enumeration value="SWC-IMPLEMENTATION"/>
 *     &lt;enumeration value="SWC-TIMING"/>
 *     &lt;enumeration value="SYSTEM"/>
 *     &lt;enumeration value="SYSTEM-SIGNAL"/>
 *     &lt;enumeration value="SYSTEM-SIGNAL-GROUP"/>
 *     &lt;enumeration value="SYSTEM-TIMING"/>
 *     &lt;enumeration value="TIMING-EXTENSION"/>
 *     &lt;enumeration value="TP-CONFIG"/>
 *     &lt;enumeration value="TRIGGER-INTERFACE"/>
 *     &lt;enumeration value="TTCAN-CLUSTER"/>
 *     &lt;enumeration value="UNIT"/>
 *     &lt;enumeration value="UNIT-GROUP"/>
 *     &lt;enumeration value="USER-DEFINED-CLUSTER"/>
 *     &lt;enumeration value="USER-DEFINED-ETHERNET-FRAME"/>
 *     &lt;enumeration value="USER-DEFINED-I-PDU"/>
 *     &lt;enumeration value="USER-DEFINED-PDU"/>
 *     &lt;enumeration value="VFB-TIMING"/>
 *     &lt;enumeration value="VIEW-MAP-SET"/>
 *     &lt;enumeration value="XCP-PDU"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "COLLECTABLE-ELEMENT--SUBTYPES-ENUM")
@XmlEnum
public enum COLLECTABLEELEMENTSUBTYPESENUM {

    @XmlEnumValue("AR-ELEMENT")
    AR___ELEMENT("AR-ELEMENT"),
    @XmlEnumValue("AR-PACKAGE")
    AR___PACKAGE("AR-PACKAGE"),
    @XmlEnumValue("ABSTRACT-CAN-CLUSTER")
    ABSTRACT___CAN___CLUSTER("ABSTRACT-CAN-CLUSTER"),
    @XmlEnumValue("ACL-OBJECT-SET")
    ACL___OBJECT___SET("ACL-OBJECT-SET"),
    @XmlEnumValue("ACL-OPERATION")
    ACL___OPERATION("ACL-OPERATION"),
    @XmlEnumValue("ACL-PERMISSION")
    ACL___PERMISSION("ACL-PERMISSION"),
    @XmlEnumValue("ACL-ROLE")
    ACL___ROLE("ACL-ROLE"),
    @XmlEnumValue("ALIAS-NAME-SET")
    ALIAS___NAME___SET("ALIAS-NAME-SET"),
    @XmlEnumValue("APPLICATION-ARRAY-DATA-TYPE")
    APPLICATION___ARRAY___DATA___TYPE("APPLICATION-ARRAY-DATA-TYPE"),
    @XmlEnumValue("APPLICATION-COMPOSITE-DATA-TYPE")
    APPLICATION___COMPOSITE___DATA___TYPE("APPLICATION-COMPOSITE-DATA-TYPE"),
    @XmlEnumValue("APPLICATION-DATA-TYPE")
    APPLICATION___DATA___TYPE("APPLICATION-DATA-TYPE"),
    @XmlEnumValue("APPLICATION-PRIMITIVE-DATA-TYPE")
    APPLICATION___PRIMITIVE___DATA___TYPE("APPLICATION-PRIMITIVE-DATA-TYPE"),
    @XmlEnumValue("APPLICATION-RECORD-DATA-TYPE")
    APPLICATION___RECORD___DATA___TYPE("APPLICATION-RECORD-DATA-TYPE"),
    @XmlEnumValue("APPLICATION-SW-COMPONENT-TYPE")
    APPLICATION___SW___COMPONENT___TYPE("APPLICATION-SW-COMPONENT-TYPE"),
    @XmlEnumValue("ATOMIC-SW-COMPONENT-TYPE")
    ATOMIC___SW___COMPONENT___TYPE("ATOMIC-SW-COMPONENT-TYPE"),
    @XmlEnumValue("AUTOSAR-DATA-TYPE")
    AUTOSAR___DATA___TYPE("AUTOSAR-DATA-TYPE"),
    @XmlEnumValue("BASE-TYPE")
    BASE___TYPE("BASE-TYPE"),
    @XmlEnumValue("BLUEPRINT-MAPPING-SET")
    BLUEPRINT___MAPPING___SET("BLUEPRINT-MAPPING-SET"),
    @XmlEnumValue("BSW-IMPLEMENTATION")
    BSW___IMPLEMENTATION("BSW-IMPLEMENTATION"),
    @XmlEnumValue("BSW-MODULE-DESCRIPTION")
    BSW___MODULE___DESCRIPTION("BSW-MODULE-DESCRIPTION"),
    @XmlEnumValue("BSW-MODULE-ENTRY")
    BSW___MODULE___ENTRY("BSW-MODULE-ENTRY"),
    @XmlEnumValue("BSW-MODULE-TIMING")
    BSW___MODULE___TIMING("BSW-MODULE-TIMING"),
    @XmlEnumValue("BUILD-ACTION-MANIFEST")
    BUILD___ACTION___MANIFEST("BUILD-ACTION-MANIFEST"),
    @XmlEnumValue("CALIBRATION-PARAMETER-VALUE-SET")
    CALIBRATION___PARAMETER___VALUE___SET("CALIBRATION-PARAMETER-VALUE-SET"),
    @XmlEnumValue("CAN-CLUSTER")
    CAN___CLUSTER("CAN-CLUSTER"),
    @XmlEnumValue("CAN-FRAME")
    CAN___FRAME("CAN-FRAME"),
    @XmlEnumValue("CAN-TP-CONFIG")
    CAN___TP___CONFIG("CAN-TP-CONFIG"),
    @XmlEnumValue("CLIENT-ID-DEFINITION-SET")
    CLIENT___ID___DEFINITION___SET("CLIENT-ID-DEFINITION-SET"),
    @XmlEnumValue("CLIENT-SERVER-INTERFACE")
    CLIENT___SERVER___INTERFACE("CLIENT-SERVER-INTERFACE"),
    @XmlEnumValue("COLLECTABLE-ELEMENT")
    COLLECTABLE___ELEMENT("COLLECTABLE-ELEMENT"),
    COLLECTION("COLLECTION"),
    @XmlEnumValue("COMMUNICATION-CLUSTER")
    COMMUNICATION___CLUSTER("COMMUNICATION-CLUSTER"),
    @XmlEnumValue("COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE")
    COMPLEX___DEVICE___DRIVER___SW___COMPONENT___TYPE("COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE"),
    @XmlEnumValue("COMPOSITION-SW-COMPONENT-TYPE")
    COMPOSITION___SW___COMPONENT___TYPE("COMPOSITION-SW-COMPONENT-TYPE"),
    @XmlEnumValue("COMPU-METHOD")
    COMPU___METHOD("COMPU-METHOD"),
    @XmlEnumValue("CONSISTENCY-NEEDS-BLUEPRINT-SET")
    CONSISTENCY___NEEDS___BLUEPRINT___SET("CONSISTENCY-NEEDS-BLUEPRINT-SET"),
    @XmlEnumValue("CONSTANT-SPECIFICATION")
    CONSTANT___SPECIFICATION("CONSTANT-SPECIFICATION"),
    @XmlEnumValue("CONSTANT-SPECIFICATION-MAPPING-SET")
    CONSTANT___SPECIFICATION___MAPPING___SET("CONSTANT-SPECIFICATION-MAPPING-SET"),
    @XmlEnumValue("CONTAINER-I-PDU")
    CONTAINER___I___PDU("CONTAINER-I-PDU"),
    @XmlEnumValue("COUPLING-ELEMENT")
    COUPLING___ELEMENT("COUPLING-ELEMENT"),
    @XmlEnumValue("DATA-CONSTR")
    DATA___CONSTR("DATA-CONSTR"),
    @XmlEnumValue("DATA-INTERFACE")
    DATA___INTERFACE("DATA-INTERFACE"),
    @XmlEnumValue("DATA-TRANSFORMATION-SET")
    DATA___TRANSFORMATION___SET("DATA-TRANSFORMATION-SET"),
    @XmlEnumValue("DATA-TYPE-MAPPING-SET")
    DATA___TYPE___MAPPING___SET("DATA-TYPE-MAPPING-SET"),
    @XmlEnumValue("DCM-I-PDU")
    DCM___I___PDU("DCM-I-PDU"),
    @XmlEnumValue("DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER")
    DIAGNOSTIC___ABSTRACT___DATA___IDENTIFIER("DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-ACCESS-PERMISSION")
    DIAGNOSTIC___ACCESS___PERMISSION("DIAGNOSTIC-ACCESS-PERMISSION"),
    @XmlEnumValue("DIAGNOSTIC-AGING")
    DIAGNOSTIC___AGING("DIAGNOSTIC-AGING"),
    @XmlEnumValue("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION")
    DIAGNOSTIC___CLEAR___DIAGNOSTIC___INFORMATION("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"),
    @XmlEnumValue("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS")
    DIAGNOSTIC___CLEAR___DIAGNOSTIC___INFORMATION___CLASS("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-COM-CONTROL")
    DIAGNOSTIC___COM___CONTROL("DIAGNOSTIC-COM-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-COM-CONTROL-CLASS")
    DIAGNOSTIC___COM___CONTROL___CLASS("DIAGNOSTIC-COM-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-COMMON-ELEMENT")
    DIAGNOSTIC___COMMON___ELEMENT("DIAGNOSTIC-COMMON-ELEMENT"),
    @XmlEnumValue("DIAGNOSTIC-CONDITION")
    DIAGNOSTIC___CONDITION("DIAGNOSTIC-CONDITION"),
    @XmlEnumValue("DIAGNOSTIC-CONDITION-GROUP")
    DIAGNOSTIC___CONDITION___GROUP("DIAGNOSTIC-CONDITION-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-CONNECTION")
    DIAGNOSTIC___CONNECTION("DIAGNOSTIC-CONNECTION"),
    @XmlEnumValue("DIAGNOSTIC-CONTRIBUTION-SET")
    DIAGNOSTIC___CONTRIBUTION___SET("DIAGNOSTIC-CONTRIBUTION-SET"),
    @XmlEnumValue("DIAGNOSTIC-CONTROL-DTC-SETTING")
    DIAGNOSTIC___CONTROL___DTC___SETTING("DIAGNOSTIC-CONTROL-DTC-SETTING"),
    @XmlEnumValue("DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS")
    DIAGNOSTIC___CONTROL___DTC___SETTING___CLASS("DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-CUSTOM-SERVICE-CLASS")
    DIAGNOSTIC___CUSTOM___SERVICE___CLASS("DIAGNOSTIC-CUSTOM-SERVICE-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___DATA___BY___IDENTIFIER("DIAGNOSTIC-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-IDENTIFIER")
    DIAGNOSTIC___DATA___IDENTIFIER("DIAGNOSTIC-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-IDENTIFIER-SET")
    DIAGNOSTIC___DATA___IDENTIFIER___SET("DIAGNOSTIC-DATA-IDENTIFIER-SET"),
    @XmlEnumValue("DIAGNOSTIC-DATA-TRANSFER")
    DIAGNOSTIC___DATA___TRANSFER("DIAGNOSTIC-DATA-TRANSFER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-TRANSFER-CLASS")
    DIAGNOSTIC___DATA___TRANSFER___CLASS("DIAGNOSTIC-DATA-TRANSFER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING")
    DIAGNOSTIC___DEM___PROVIDED___DATA___MAPPING("DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER")
    DIAGNOSTIC___DYNAMIC___DATA___IDENTIFIER("DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER")
    DIAGNOSTIC___DYNAMICALLY___DEFINE___DATA___IDENTIFIER("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS")
    DIAGNOSTIC___DYNAMICALLY___DEFINE___DATA___IDENTIFIER___CLASS("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ECU-RESET")
    DIAGNOSTIC___ECU___RESET("DIAGNOSTIC-ECU-RESET"),
    @XmlEnumValue("DIAGNOSTIC-ECU-RESET-CLASS")
    DIAGNOSTIC___ECU___RESET___CLASS("DIAGNOSTIC-ECU-RESET-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ENABLE-CONDITION")
    DIAGNOSTIC___ENABLE___CONDITION("DIAGNOSTIC-ENABLE-CONDITION"),
    @XmlEnumValue("DIAGNOSTIC-ENABLE-CONDITION-GROUP")
    DIAGNOSTIC___ENABLE___CONDITION___GROUP("DIAGNOSTIC-ENABLE-CONDITION-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING")
    DIAGNOSTIC___ENABLE___CONDITION___PORT___MAPPING("DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT")
    DIAGNOSTIC___EVENT("DIAGNOSTIC-EVENT"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-PORT-MAPPING")
    DIAGNOSTIC___EVENT___PORT___MAPPING("DIAGNOSTIC-EVENT-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING")
    DIAGNOSTIC___EVENT___TO___DEBOUNCE___ALGORITHM___MAPPING("DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING")
    DIAGNOSTIC___EVENT___TO___ENABLE___CONDITION___GROUP___MAPPING("DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING")
    DIAGNOSTIC___EVENT___TO___OPERATION___CYCLE___MAPPING("DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING")
    DIAGNOSTIC___EVENT___TO___STORAGE___CONDITION___GROUP___MAPPING("DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING")
    DIAGNOSTIC___EVENT___TO___TROUBLE___CODE___UDS___MAPPING("DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EXTENDED-DATA-RECORD")
    DIAGNOSTIC___EXTENDED___DATA___RECORD("DIAGNOSTIC-EXTENDED-DATA-RECORD"),
    @XmlEnumValue("DIAGNOSTIC-FREEZE-FRAME")
    DIAGNOSTIC___FREEZE___FRAME("DIAGNOSTIC-FREEZE-FRAME"),
    @XmlEnumValue("DIAGNOSTIC-IO-CONTROL")
    DIAGNOSTIC___IO___CONTROL("DIAGNOSTIC-IO-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-INDICATOR")
    DIAGNOSTIC___INDICATOR("DIAGNOSTIC-INDICATOR"),
    @XmlEnumValue("DIAGNOSTIC-IO-CONTROL-CLASS")
    DIAGNOSTIC___IO___CONTROL___CLASS("DIAGNOSTIC-IO-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-MAPPING")
    DIAGNOSTIC___MAPPING("DIAGNOSTIC-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS")
    DIAGNOSTIC___MEMORY___ADDRESSABLE___RANGE___ACCESS("DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___MEMORY___BY___ADDRESS("DIAGNOSTIC-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION")
    DIAGNOSTIC___MEMORY___DESTINATION("DIAGNOSTIC-MEMORY-DESTINATION"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION-MIRROR")
    DIAGNOSTIC___MEMORY___DESTINATION___MIRROR("DIAGNOSTIC-MEMORY-DESTINATION-MIRROR"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY")
    DIAGNOSTIC___MEMORY___DESTINATION___PRIMARY("DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED")
    DIAGNOSTIC___MEMORY___DESTINATION___USER___DEFINED("DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-IDENTIFIER")
    DIAGNOSTIC___MEMORY___IDENTIFIER("DIAGNOSTIC-MEMORY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-OPERATION-CYCLE")
    DIAGNOSTIC___OPERATION___CYCLE("DIAGNOSTIC-OPERATION-CYCLE"),
    @XmlEnumValue("DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING")
    DIAGNOSTIC___OPERATION___CYCLE___PORT___MAPPING("DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-READ-DTC-INFORMATION")
    DIAGNOSTIC___READ___DTC___INFORMATION("DIAGNOSTIC-READ-DTC-INFORMATION"),
    @XmlEnumValue("DIAGNOSTIC-READ-DTC-INFORMATION-CLASS")
    DIAGNOSTIC___READ___DTC___INFORMATION___CLASS("DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___READ___DATA___BY___IDENTIFIER("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS")
    DIAGNOSTIC___READ___DATA___BY___IDENTIFIER___CLASS("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID")
    DIAGNOSTIC___READ___DATA___BY___PERIODIC___ID("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS")
    DIAGNOSTIC___READ___DATA___BY___PERIODIC___ID___CLASS("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___READ___MEMORY___BY___ADDRESS("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS")
    DIAGNOSTIC___READ___MEMORY___BY___ADDRESS___CLASS("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-DOWNLOAD")
    DIAGNOSTIC___REQUEST___DOWNLOAD("DIAGNOSTIC-REQUEST-DOWNLOAD"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS")
    DIAGNOSTIC___REQUEST___DOWNLOAD___CLASS("DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-FILE-TRANSFER")
    DIAGNOSTIC___REQUEST___FILE___TRANSFER("DIAGNOSTIC-REQUEST-FILE-TRANSFER"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS")
    DIAGNOSTIC___REQUEST___FILE___TRANSFER___CLASS("DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-UPLOAD")
    DIAGNOSTIC___REQUEST___UPLOAD("DIAGNOSTIC-REQUEST-UPLOAD"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-UPLOAD-CLASS")
    DIAGNOSTIC___REQUEST___UPLOAD___CLASS("DIAGNOSTIC-REQUEST-UPLOAD-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-RESPONSE-ON-EVENT")
    DIAGNOSTIC___RESPONSE___ON___EVENT("DIAGNOSTIC-RESPONSE-ON-EVENT"),
    @XmlEnumValue("DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS")
    DIAGNOSTIC___RESPONSE___ON___EVENT___CLASS("DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE")
    DIAGNOSTIC___ROUTINE("DIAGNOSTIC-ROUTINE"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE-CONTROL")
    DIAGNOSTIC___ROUTINE___CONTROL("DIAGNOSTIC-ROUTINE-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE-CONTROL-CLASS")
    DIAGNOSTIC___ROUTINE___CONTROL___CLASS("DIAGNOSTIC-ROUTINE-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-ACCESS")
    DIAGNOSTIC___SECURITY___ACCESS("DIAGNOSTIC-SECURITY-ACCESS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-ACCESS-CLASS")
    DIAGNOSTIC___SECURITY___ACCESS___CLASS("DIAGNOSTIC-SECURITY-ACCESS-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-LEVEL")
    DIAGNOSTIC___SECURITY___LEVEL("DIAGNOSTIC-SECURITY-LEVEL"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-CLASS")
    DIAGNOSTIC___SERVICE___CLASS("DIAGNOSTIC-SERVICE-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-DATA-MAPPING")
    DIAGNOSTIC___SERVICE___DATA___MAPPING("DIAGNOSTIC-SERVICE-DATA-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-INSTANCE")
    DIAGNOSTIC___SERVICE___INSTANCE("DIAGNOSTIC-SERVICE-INSTANCE"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-SW-MAPPING")
    DIAGNOSTIC___SERVICE___SW___MAPPING("DIAGNOSTIC-SERVICE-SW-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-TABLE")
    DIAGNOSTIC___SERVICE___TABLE("DIAGNOSTIC-SERVICE-TABLE"),
    @XmlEnumValue("DIAGNOSTIC-SESSION")
    DIAGNOSTIC___SESSION("DIAGNOSTIC-SESSION"),
    @XmlEnumValue("DIAGNOSTIC-SESSION-CONTROL")
    DIAGNOSTIC___SESSION___CONTROL("DIAGNOSTIC-SESSION-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-SESSION-CONTROL-CLASS")
    DIAGNOSTIC___SESSION___CONTROL___CLASS("DIAGNOSTIC-SESSION-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-STORAGE-CONDITION")
    DIAGNOSTIC___STORAGE___CONDITION("DIAGNOSTIC-STORAGE-CONDITION"),
    @XmlEnumValue("DIAGNOSTIC-STORAGE-CONDITION-GROUP")
    DIAGNOSTIC___STORAGE___CONDITION___GROUP("DIAGNOSTIC-STORAGE-CONDITION-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING")
    DIAGNOSTIC___STORAGE___CONDITION___PORT___MAPPING("DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-SW-MAPPING")
    DIAGNOSTIC___SW___MAPPING("DIAGNOSTIC-SW-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-TRANSFER-EXIT")
    DIAGNOSTIC___TRANSFER___EXIT("DIAGNOSTIC-TRANSFER-EXIT"),
    @XmlEnumValue("DIAGNOSTIC-TRANSFER-EXIT-CLASS")
    DIAGNOSTIC___TRANSFER___EXIT___CLASS("DIAGNOSTIC-TRANSFER-EXIT-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE")
    DIAGNOSTIC___TROUBLE___CODE("DIAGNOSTIC-TROUBLE-CODE"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-GROUP")
    DIAGNOSTIC___TROUBLE___CODE___GROUP("DIAGNOSTIC-TROUBLE-CODE-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-J-1939")
    DIAGNOSTIC___TROUBLE___CODE___J___1939("DIAGNOSTIC-TROUBLE-CODE-J-1939"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-OBD")
    DIAGNOSTIC___TROUBLE___CODE___OBD("DIAGNOSTIC-TROUBLE-CODE-OBD"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-PROPS")
    DIAGNOSTIC___TROUBLE___CODE___PROPS("DIAGNOSTIC-TROUBLE-CODE-PROPS"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-UDS")
    DIAGNOSTIC___TROUBLE___CODE___UDS("DIAGNOSTIC-TROUBLE-CODE-UDS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___WRITE___DATA___BY___IDENTIFIER("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS")
    DIAGNOSTIC___WRITE___DATA___BY___IDENTIFIER___CLASS("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___WRITE___MEMORY___BY___ADDRESS("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS")
    DIAGNOSTIC___WRITE___MEMORY___BY___ADDRESS___CLASS("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS"),
    DOCUMENTATION("DOCUMENTATION"),
    @XmlEnumValue("ECU-ABSTRACTION-SW-COMPONENT-TYPE")
    ECU___ABSTRACTION___SW___COMPONENT___TYPE("ECU-ABSTRACTION-SW-COMPONENT-TYPE"),
    @XmlEnumValue("ECU-INSTANCE")
    ECU___INSTANCE("ECU-INSTANCE"),
    @XmlEnumValue("ECU-TIMING")
    ECU___TIMING("ECU-TIMING"),
    @XmlEnumValue("ECUC-DEFINITION-COLLECTION")
    ECUC___DEFINITION___COLLECTION("ECUC-DEFINITION-COLLECTION"),
    @XmlEnumValue("ECUC-DESTINATION-URI-DEF-SET")
    ECUC___DESTINATION___URI___DEF___SET("ECUC-DESTINATION-URI-DEF-SET"),
    @XmlEnumValue("ECUC-MODULE-CONFIGURATION-VALUES")
    ECUC___MODULE___CONFIGURATION___VALUES("ECUC-MODULE-CONFIGURATION-VALUES"),
    @XmlEnumValue("ECUC-MODULE-DEF")
    ECUC___MODULE___DEF("ECUC-MODULE-DEF"),
    @XmlEnumValue("ECUC-VALUE-COLLECTION")
    ECUC___VALUE___COLLECTION("ECUC-VALUE-COLLECTION"),
    @XmlEnumValue("END-TO-END-PROTECTION-SET")
    END___TO___END___PROTECTION___SET("END-TO-END-PROTECTION-SET"),
    @XmlEnumValue("ETHERNET-CLUSTER")
    ETHERNET___CLUSTER("ETHERNET-CLUSTER"),
    @XmlEnumValue("ETHERNET-FRAME")
    ETHERNET___FRAME("ETHERNET-FRAME"),
    @XmlEnumValue("EVALUATED-VARIANT-SET")
    EVALUATED___VARIANT___SET("EVALUATED-VARIANT-SET"),
    @XmlEnumValue("FM-FEATURE")
    FM___FEATURE("FM-FEATURE"),
    @XmlEnumValue("FM-FEATURE-MAP")
    FM___FEATURE___MAP("FM-FEATURE-MAP"),
    @XmlEnumValue("FM-FEATURE-MODEL")
    FM___FEATURE___MODEL("FM-FEATURE-MODEL"),
    @XmlEnumValue("FM-FEATURE-SELECTION-SET")
    FM___FEATURE___SELECTION___SET("FM-FEATURE-SELECTION-SET"),
    @XmlEnumValue("FIBEX-ELEMENT")
    FIBEX___ELEMENT("FIBEX-ELEMENT"),
    @XmlEnumValue("FLAT-MAP")
    FLAT___MAP("FLAT-MAP"),
    @XmlEnumValue("FLEXRAY-AR-TP-CONFIG")
    FLEXRAY___AR___TP___CONFIG("FLEXRAY-AR-TP-CONFIG"),
    @XmlEnumValue("FLEXRAY-CLUSTER")
    FLEXRAY___CLUSTER("FLEXRAY-CLUSTER"),
    @XmlEnumValue("FLEXRAY-FRAME")
    FLEXRAY___FRAME("FLEXRAY-FRAME"),
    @XmlEnumValue("FLEXRAY-TP-CONFIG")
    FLEXRAY___TP___CONFIG("FLEXRAY-TP-CONFIG"),
    FRAME("FRAME"),
    GATEWAY("GATEWAY"),
    @XmlEnumValue("GENERAL-PURPOSE-I-PDU")
    GENERAL___PURPOSE___I___PDU("GENERAL-PURPOSE-I-PDU"),
    @XmlEnumValue("GENERAL-PURPOSE-PDU")
    GENERAL___PURPOSE___PDU("GENERAL-PURPOSE-PDU"),
    @XmlEnumValue("GENERIC-ETHERNET-FRAME")
    GENERIC___ETHERNET___FRAME("GENERIC-ETHERNET-FRAME"),
    @XmlEnumValue("GLOBAL-TIME-DOMAIN")
    GLOBAL___TIME___DOMAIN("GLOBAL-TIME-DOMAIN"),
    @XmlEnumValue("HW-CATEGORY")
    HW___CATEGORY("HW-CATEGORY"),
    @XmlEnumValue("HW-ELEMENT")
    HW___ELEMENT("HW-ELEMENT"),
    @XmlEnumValue("HW-TYPE")
    HW___TYPE("HW-TYPE"),
    @XmlEnumValue("I-PDU")
    I___PDU("I-PDU"),
    @XmlEnumValue("I-SIGNAL")
    I___SIGNAL("I-SIGNAL"),
    @XmlEnumValue("I-SIGNAL-GROUP")
    I___SIGNAL___GROUP("I-SIGNAL-GROUP"),
    @XmlEnumValue("I-SIGNAL-I-PDU")
    I___SIGNAL___I___PDU("I-SIGNAL-I-PDU"),
    @XmlEnumValue("I-SIGNAL-I-PDU-GROUP")
    I___SIGNAL___I___PDU___GROUP("I-SIGNAL-I-PDU-GROUP"),
    @XmlEnumValue("IEEE-1722-TP-ETHERNET-FRAME")
    IEEE___1722___TP___ETHERNET___FRAME("IEEE-1722-TP-ETHERNET-FRAME"),
    IMPLEMENTATION("IMPLEMENTATION"),
    @XmlEnumValue("IMPLEMENTATION-DATA-TYPE")
    IMPLEMENTATION___DATA___TYPE("IMPLEMENTATION-DATA-TYPE"),
    @XmlEnumValue("INTERPOLATION-ROUTINE-MAPPING-SET")
    INTERPOLATION___ROUTINE___MAPPING___SET("INTERPOLATION-ROUTINE-MAPPING-SET"),
    @XmlEnumValue("J-1939-CLUSTER")
    J___1939___CLUSTER("J-1939-CLUSTER"),
    @XmlEnumValue("J-1939-DCM-I-PDU")
    J___1939___DCM___I___PDU("J-1939-DCM-I-PDU"),
    @XmlEnumValue("J-1939-TP-CONFIG")
    J___1939___TP___CONFIG("J-1939-TP-CONFIG"),
    @XmlEnumValue("KEYWORD-SET")
    KEYWORD___SET("KEYWORD-SET"),
    @XmlEnumValue("LIFE-CYCLE-INFO-SET")
    LIFE___CYCLE___INFO___SET("LIFE-CYCLE-INFO-SET"),
    @XmlEnumValue("LIFE-CYCLE-STATE-DEFINITION-GROUP")
    LIFE___CYCLE___STATE___DEFINITION___GROUP("LIFE-CYCLE-STATE-DEFINITION-GROUP"),
    @XmlEnumValue("LIN-CLUSTER")
    LIN___CLUSTER("LIN-CLUSTER"),
    @XmlEnumValue("LIN-EVENT-TRIGGERED-FRAME")
    LIN___EVENT___TRIGGERED___FRAME("LIN-EVENT-TRIGGERED-FRAME"),
    @XmlEnumValue("LIN-FRAME")
    LIN___FRAME("LIN-FRAME"),
    @XmlEnumValue("LIN-SPORADIC-FRAME")
    LIN___SPORADIC___FRAME("LIN-SPORADIC-FRAME"),
    @XmlEnumValue("LIN-TP-CONFIG")
    LIN___TP___CONFIG("LIN-TP-CONFIG"),
    @XmlEnumValue("LIN-UNCONDITIONAL-FRAME")
    LIN___UNCONDITIONAL___FRAME("LIN-UNCONDITIONAL-FRAME"),
    @XmlEnumValue("MC-FUNCTION")
    MC___FUNCTION("MC-FUNCTION"),
    @XmlEnumValue("MODE-DECLARATION-GROUP")
    MODE___DECLARATION___GROUP("MODE-DECLARATION-GROUP"),
    @XmlEnumValue("MODE-DECLARATION-MAPPING-SET")
    MODE___DECLARATION___MAPPING___SET("MODE-DECLARATION-MAPPING-SET"),
    @XmlEnumValue("MODE-SWITCH-INTERFACE")
    MODE___SWITCH___INTERFACE("MODE-SWITCH-INTERFACE"),
    @XmlEnumValue("MULTIPLEXED-I-PDU")
    MULTIPLEXED___I___PDU("MULTIPLEXED-I-PDU"),
    @XmlEnumValue("N-PDU")
    N___PDU("N-PDU"),
    @XmlEnumValue("NM-CONFIG")
    NM___CONFIG("NM-CONFIG"),
    @XmlEnumValue("NM-PDU")
    NM___PDU("NM-PDU"),
    @XmlEnumValue("NV-BLOCK-SW-COMPONENT-TYPE")
    NV___BLOCK___SW___COMPONENT___TYPE("NV-BLOCK-SW-COMPONENT-TYPE"),
    @XmlEnumValue("NV-DATA-INTERFACE")
    NV___DATA___INTERFACE("NV-DATA-INTERFACE"),
    @XmlEnumValue("PACKAGEABLE-ELEMENT")
    PACKAGEABLE___ELEMENT("PACKAGEABLE-ELEMENT"),
    @XmlEnumValue("PARAMETER-INTERFACE")
    PARAMETER___INTERFACE("PARAMETER-INTERFACE"),
    @XmlEnumValue("PARAMETER-SW-COMPONENT-TYPE")
    PARAMETER___SW___COMPONENT___TYPE("PARAMETER-SW-COMPONENT-TYPE"),
    PDU("PDU"),
    @XmlEnumValue("PDUR-I-PDU-GROUP")
    PDUR___I___PDU___GROUP("PDUR-I-PDU-GROUP"),
    @XmlEnumValue("PHYSICAL-DIMENSION")
    PHYSICAL___DIMENSION("PHYSICAL-DIMENSION"),
    @XmlEnumValue("PHYSICAL-DIMENSION-MAPPING-SET")
    PHYSICAL___DIMENSION___MAPPING___SET("PHYSICAL-DIMENSION-MAPPING-SET"),
    @XmlEnumValue("PORT-INTERFACE")
    PORT___INTERFACE("PORT-INTERFACE"),
    @XmlEnumValue("PORT-INTERFACE-MAPPING-SET")
    PORT___INTERFACE___MAPPING___SET("PORT-INTERFACE-MAPPING-SET"),
    @XmlEnumValue("PORT-PROTOTYPE-BLUEPRINT")
    PORT___PROTOTYPE___BLUEPRINT("PORT-PROTOTYPE-BLUEPRINT"),
    @XmlEnumValue("POST-BUILD-VARIANT-CRITERION")
    POST___BUILD___VARIANT___CRITERION("POST-BUILD-VARIANT-CRITERION"),
    @XmlEnumValue("POST-BUILD-VARIANT-CRITERION-VALUE-SET")
    POST___BUILD___VARIANT___CRITERION___VALUE___SET("POST-BUILD-VARIANT-CRITERION-VALUE-SET"),
    @XmlEnumValue("PREDEFINED-VARIANT")
    PREDEFINED___VARIANT("PREDEFINED-VARIANT"),
    @XmlEnumValue("RAPID-PROTOTYPING-SCENARIO")
    RAPID___PROTOTYPING___SCENARIO("RAPID-PROTOTYPING-SCENARIO"),
    @XmlEnumValue("SECURED-I-PDU")
    SECURED___I___PDU("SECURED-I-PDU"),
    @XmlEnumValue("SENDER-RECEIVER-INTERFACE")
    SENDER___RECEIVER___INTERFACE("SENDER-RECEIVER-INTERFACE"),
    @XmlEnumValue("SENSOR-ACTUATOR-SW-COMPONENT-TYPE")
    SENSOR___ACTUATOR___SW___COMPONENT___TYPE("SENSOR-ACTUATOR-SW-COMPONENT-TYPE"),
    @XmlEnumValue("SERIALIZATION-TECHNOLOGY")
    SERIALIZATION___TECHNOLOGY("SERIALIZATION-TECHNOLOGY"),
    @XmlEnumValue("SERVICE-PROXY-SW-COMPONENT-TYPE")
    SERVICE___PROXY___SW___COMPONENT___TYPE("SERVICE-PROXY-SW-COMPONENT-TYPE"),
    @XmlEnumValue("SERVICE-SW-COMPONENT-TYPE")
    SERVICE___SW___COMPONENT___TYPE("SERVICE-SW-COMPONENT-TYPE"),
    @XmlEnumValue("SO-AD-ROUTING-GROUP")
    SO___AD___ROUTING___GROUP("SO-AD-ROUTING-GROUP"),
    @XmlEnumValue("SW-ADDR-METHOD")
    SW___ADDR___METHOD("SW-ADDR-METHOD"),
    @XmlEnumValue("SW-AXIS-TYPE")
    SW___AXIS___TYPE("SW-AXIS-TYPE"),
    @XmlEnumValue("SW-BASE-TYPE")
    SW___BASE___TYPE("SW-BASE-TYPE"),
    @XmlEnumValue("SW-COMPONENT-TYPE")
    SW___COMPONENT___TYPE("SW-COMPONENT-TYPE"),
    @XmlEnumValue("SW-RECORD-LAYOUT")
    SW___RECORD___LAYOUT("SW-RECORD-LAYOUT"),
    @XmlEnumValue("SW-SYSTEMCONST")
    SW___SYSTEMCONST("SW-SYSTEMCONST"),
    @XmlEnumValue("SW-SYSTEMCONSTANT-VALUE-SET")
    SW___SYSTEMCONSTANT___VALUE___SET("SW-SYSTEMCONSTANT-VALUE-SET"),
    @XmlEnumValue("SWC-BSW-MAPPING")
    SWC___BSW___MAPPING("SWC-BSW-MAPPING"),
    @XmlEnumValue("SWC-IMPLEMENTATION")
    SWC___IMPLEMENTATION("SWC-IMPLEMENTATION"),
    @XmlEnumValue("SWC-TIMING")
    SWC___TIMING("SWC-TIMING"),
    SYSTEM("SYSTEM"),
    @XmlEnumValue("SYSTEM-SIGNAL")
    SYSTEM___SIGNAL("SYSTEM-SIGNAL"),
    @XmlEnumValue("SYSTEM-SIGNAL-GROUP")
    SYSTEM___SIGNAL___GROUP("SYSTEM-SIGNAL-GROUP"),
    @XmlEnumValue("SYSTEM-TIMING")
    SYSTEM___TIMING("SYSTEM-TIMING"),
    @XmlEnumValue("TIMING-EXTENSION")
    TIMING___EXTENSION("TIMING-EXTENSION"),
    @XmlEnumValue("TP-CONFIG")
    TP___CONFIG("TP-CONFIG"),
    @XmlEnumValue("TRIGGER-INTERFACE")
    TRIGGER___INTERFACE("TRIGGER-INTERFACE"),
    @XmlEnumValue("TTCAN-CLUSTER")
    TTCAN___CLUSTER("TTCAN-CLUSTER"),
    UNIT("UNIT"),
    @XmlEnumValue("UNIT-GROUP")
    UNIT___GROUP("UNIT-GROUP"),
    @XmlEnumValue("USER-DEFINED-CLUSTER")
    USER___DEFINED___CLUSTER("USER-DEFINED-CLUSTER"),
    @XmlEnumValue("USER-DEFINED-ETHERNET-FRAME")
    USER___DEFINED___ETHERNET___FRAME("USER-DEFINED-ETHERNET-FRAME"),
    @XmlEnumValue("USER-DEFINED-I-PDU")
    USER___DEFINED___I___PDU("USER-DEFINED-I-PDU"),
    @XmlEnumValue("USER-DEFINED-PDU")
    USER___DEFINED___PDU("USER-DEFINED-PDU"),
    @XmlEnumValue("VFB-TIMING")
    VFB___TIMING("VFB-TIMING"),
    @XmlEnumValue("VIEW-MAP-SET")
    VIEW___MAP___SET("VIEW-MAP-SET"),
    @XmlEnumValue("XCP-PDU")
    XCP___PDU("XCP-PDU");
    private final String value;

    COLLECTABLEELEMENTSUBTYPESENUM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static COLLECTABLEELEMENTSUBTYPESENUM fromValue(String v) {
        for (COLLECTABLEELEMENTSUBTYPESENUM c: COLLECTABLEELEMENTSUBTYPESENUM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
