//
// ????? JavaTM Architecture for XML Binding (JAXB) ???? v2.2.8-b130911.1802 ???
// ??? <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// ?????????, ??????????????
// ????: 2018.03.12 ?? 11:42:22 PM CET 
//


package Ar421;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>DIAGNOSTIC-SERVICE-INSTANCE--SUBTYPES-ENUM? Java ??
 * 
 * <p>????????????????????
 * <p>
 * <pre>
 * &lt;simpleType name="DIAGNOSTIC-SERVICE-INSTANCE--SUBTYPES-ENUM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-COM-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTROL-DTC-SETTING"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-TRANSFER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-ECU-RESET"/>
 *     &lt;enumeration value="DIAGNOSTIC-IO-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DTC-INFORMATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-DOWNLOAD"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-FILE-TRANSFER"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-UPLOAD"/>
 *     &lt;enumeration value="DIAGNOSTIC-RESPONSE-ON-EVENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-ACCESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-INSTANCE"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-TRANSFER-EXIT"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DIAGNOSTIC-SERVICE-INSTANCE--SUBTYPES-ENUM")
@XmlEnum
public enum DIAGNOSTICSERVICEINSTANCESUBTYPESENUM {

    @XmlEnumValue("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION")
    DIAGNOSTIC___CLEAR___DIAGNOSTIC___INFORMATION("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"),
    @XmlEnumValue("DIAGNOSTIC-COM-CONTROL")
    DIAGNOSTIC___COM___CONTROL("DIAGNOSTIC-COM-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-CONTROL-DTC-SETTING")
    DIAGNOSTIC___CONTROL___DTC___SETTING("DIAGNOSTIC-CONTROL-DTC-SETTING"),
    @XmlEnumValue("DIAGNOSTIC-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___DATA___BY___IDENTIFIER("DIAGNOSTIC-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-TRANSFER")
    DIAGNOSTIC___DATA___TRANSFER("DIAGNOSTIC-DATA-TRANSFER"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER")
    DIAGNOSTIC___DYNAMICALLY___DEFINE___DATA___IDENTIFIER("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-ECU-RESET")
    DIAGNOSTIC___ECU___RESET("DIAGNOSTIC-ECU-RESET"),
    @XmlEnumValue("DIAGNOSTIC-IO-CONTROL")
    DIAGNOSTIC___IO___CONTROL("DIAGNOSTIC-IO-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS")
    DIAGNOSTIC___MEMORY___ADDRESSABLE___RANGE___ACCESS("DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___MEMORY___BY___ADDRESS("DIAGNOSTIC-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DTC-INFORMATION")
    DIAGNOSTIC___READ___DTC___INFORMATION("DIAGNOSTIC-READ-DTC-INFORMATION"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___READ___DATA___BY___IDENTIFIER("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID")
    DIAGNOSTIC___READ___DATA___BY___PERIODIC___ID("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"),
    @XmlEnumValue("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___READ___MEMORY___BY___ADDRESS("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-DOWNLOAD")
    DIAGNOSTIC___REQUEST___DOWNLOAD("DIAGNOSTIC-REQUEST-DOWNLOAD"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-FILE-TRANSFER")
    DIAGNOSTIC___REQUEST___FILE___TRANSFER("DIAGNOSTIC-REQUEST-FILE-TRANSFER"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-UPLOAD")
    DIAGNOSTIC___REQUEST___UPLOAD("DIAGNOSTIC-REQUEST-UPLOAD"),
    @XmlEnumValue("DIAGNOSTIC-RESPONSE-ON-EVENT")
    DIAGNOSTIC___RESPONSE___ON___EVENT("DIAGNOSTIC-RESPONSE-ON-EVENT"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE-CONTROL")
    DIAGNOSTIC___ROUTINE___CONTROL("DIAGNOSTIC-ROUTINE-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-ACCESS")
    DIAGNOSTIC___SECURITY___ACCESS("DIAGNOSTIC-SECURITY-ACCESS"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-INSTANCE")
    DIAGNOSTIC___SERVICE___INSTANCE("DIAGNOSTIC-SERVICE-INSTANCE"),
    @XmlEnumValue("DIAGNOSTIC-SESSION-CONTROL")
    DIAGNOSTIC___SESSION___CONTROL("DIAGNOSTIC-SESSION-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-TRANSFER-EXIT")
    DIAGNOSTIC___TRANSFER___EXIT("DIAGNOSTIC-TRANSFER-EXIT"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___WRITE___DATA___BY___IDENTIFIER("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___WRITE___MEMORY___BY___ADDRESS("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS");
    private final String value;

    DIAGNOSTICSERVICEINSTANCESUBTYPESENUM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DIAGNOSTICSERVICEINSTANCESUBTYPESENUM fromValue(String v) {
        for (DIAGNOSTICSERVICEINSTANCESUBTYPESENUM c: DIAGNOSTICSERVICEINSTANCESUBTYPESENUM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
