//
// ????? JavaTM Architecture for XML Binding (JAXB) ???? v2.2.8-b130911.1802 ???
// ??? <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// ?????????, ??????????????
// ????: 2018.03.12 ?? 11:42:22 PM CET 
//


package Ar421;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>DIAGNOSTIC-SERVICE-CLASS--SUBTYPES-ENUM? Java ??
 * 
 * <p>????????????????????
 * <p>
 * <pre>
 * &lt;simpleType name="DIAGNOSTIC-SERVICE-CLASS--SUBTYPES-ENUM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-COM-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-CUSTOM-SERVICE-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-TRANSFER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ECU-RESET-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-IO-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-UPLOAD-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-ACCESS-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-TRANSFER-EXIT-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DIAGNOSTIC-SERVICE-CLASS--SUBTYPES-ENUM")
@XmlEnum
public enum DIAGNOSTICSERVICECLASSSUBTYPESENUM {

    @XmlEnumValue("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS")
    DIAGNOSTIC___CLEAR___DIAGNOSTIC___INFORMATION___CLASS("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-COM-CONTROL-CLASS")
    DIAGNOSTIC___COM___CONTROL___CLASS("DIAGNOSTIC-COM-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS")
    DIAGNOSTIC___CONTROL___DTC___SETTING___CLASS("DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-CUSTOM-SERVICE-CLASS")
    DIAGNOSTIC___CUSTOM___SERVICE___CLASS("DIAGNOSTIC-CUSTOM-SERVICE-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-DATA-TRANSFER-CLASS")
    DIAGNOSTIC___DATA___TRANSFER___CLASS("DIAGNOSTIC-DATA-TRANSFER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS")
    DIAGNOSTIC___DYNAMICALLY___DEFINE___DATA___IDENTIFIER___CLASS("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ECU-RESET-CLASS")
    DIAGNOSTIC___ECU___RESET___CLASS("DIAGNOSTIC-ECU-RESET-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-IO-CONTROL-CLASS")
    DIAGNOSTIC___IO___CONTROL___CLASS("DIAGNOSTIC-IO-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DTC-INFORMATION-CLASS")
    DIAGNOSTIC___READ___DTC___INFORMATION___CLASS("DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS")
    DIAGNOSTIC___READ___DATA___BY___IDENTIFIER___CLASS("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS")
    DIAGNOSTIC___READ___DATA___BY___PERIODIC___ID___CLASS("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS")
    DIAGNOSTIC___READ___MEMORY___BY___ADDRESS___CLASS("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS")
    DIAGNOSTIC___REQUEST___DOWNLOAD___CLASS("DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS")
    DIAGNOSTIC___REQUEST___FILE___TRANSFER___CLASS("DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-UPLOAD-CLASS")
    DIAGNOSTIC___REQUEST___UPLOAD___CLASS("DIAGNOSTIC-REQUEST-UPLOAD-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS")
    DIAGNOSTIC___RESPONSE___ON___EVENT___CLASS("DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE-CONTROL-CLASS")
    DIAGNOSTIC___ROUTINE___CONTROL___CLASS("DIAGNOSTIC-ROUTINE-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-ACCESS-CLASS")
    DIAGNOSTIC___SECURITY___ACCESS___CLASS("DIAGNOSTIC-SECURITY-ACCESS-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-CLASS")
    DIAGNOSTIC___SERVICE___CLASS("DIAGNOSTIC-SERVICE-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SESSION-CONTROL-CLASS")
    DIAGNOSTIC___SESSION___CONTROL___CLASS("DIAGNOSTIC-SESSION-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-TRANSFER-EXIT-CLASS")
    DIAGNOSTIC___TRANSFER___EXIT___CLASS("DIAGNOSTIC-TRANSFER-EXIT-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS")
    DIAGNOSTIC___WRITE___DATA___BY___IDENTIFIER___CLASS("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS")
    DIAGNOSTIC___WRITE___MEMORY___BY___ADDRESS___CLASS("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS");
    private final String value;

    DIAGNOSTICSERVICECLASSSUBTYPESENUM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DIAGNOSTICSERVICECLASSSUBTYPESENUM fromValue(String v) {
        for (DIAGNOSTICSERVICECLASSSUBTYPESENUM c: DIAGNOSTICSERVICECLASSSUBTYPESENUM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
