//
// ????? JavaTM Architecture for XML Binding (JAXB) ???? v2.2.8-b130911.1802 ???
// ??? <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// ?????????, ??????????????
// ????: 2018.03.12 ?? 11:42:22 PM CET 
//


package Ar421;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>DIAGNOSTIC-COMMON-ELEMENT--SUBTYPES-ENUM? Java ??
 * 
 * <p>????????????????????
 * <p>
 * <pre>
 * &lt;simpleType name="DIAGNOSTIC-COMMON-ELEMENT--SUBTYPES-ENUM">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-ACCESS-PERMISSION"/>
 *     &lt;enumeration value="DIAGNOSTIC-AGING"/>
 *     &lt;enumeration value="DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-COM-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-COM-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-COMMON-ELEMENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONDITION"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONDITION-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTROL-DTC-SETTING"/>
 *     &lt;enumeration value="DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-CUSTOM-SERVICE-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-IDENTIFIER-SET"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-TRANSFER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DATA-TRANSFER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ECU-RESET"/>
 *     &lt;enumeration value="DIAGNOSTIC-ECU-RESET-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ENABLE-CONDITION"/>
 *     &lt;enumeration value="DIAGNOSTIC-ENABLE-CONDITION-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-EXTENDED-DATA-RECORD"/>
 *     &lt;enumeration value="DIAGNOSTIC-FREEZE-FRAME"/>
 *     &lt;enumeration value="DIAGNOSTIC-IO-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-INDICATOR"/>
 *     &lt;enumeration value="DIAGNOSTIC-IO-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION-MIRROR"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED"/>
 *     &lt;enumeration value="DIAGNOSTIC-MEMORY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-OPERATION-CYCLE"/>
 *     &lt;enumeration value="DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DTC-INFORMATION"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-DOWNLOAD"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-FILE-TRANSFER"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-UPLOAD"/>
 *     &lt;enumeration value="DIAGNOSTIC-REQUEST-UPLOAD-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-RESPONSE-ON-EVENT"/>
 *     &lt;enumeration value="DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-ROUTINE-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-ACCESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-ACCESS-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SECURITY-LEVEL"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-DATA-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-INSTANCE"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-SW-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-SERVICE-TABLE"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION-CONTROL"/>
 *     &lt;enumeration value="DIAGNOSTIC-SESSION-CONTROL-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-STORAGE-CONDITION"/>
 *     &lt;enumeration value="DIAGNOSTIC-STORAGE-CONDITION-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-SW-MAPPING"/>
 *     &lt;enumeration value="DIAGNOSTIC-TRANSFER-EXIT"/>
 *     &lt;enumeration value="DIAGNOSTIC-TRANSFER-EXIT-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-GROUP"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-J-1939"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-OBD"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-PROPS"/>
 *     &lt;enumeration value="DIAGNOSTIC-TROUBLE-CODE-UDS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS"/>
 *     &lt;enumeration value="DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DIAGNOSTIC-COMMON-ELEMENT--SUBTYPES-ENUM")
@XmlEnum
public enum DIAGNOSTICCOMMONELEMENTSUBTYPESENUM {

    @XmlEnumValue("DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER")
    DIAGNOSTIC___ABSTRACT___DATA___IDENTIFIER("DIAGNOSTIC-ABSTRACT-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-ACCESS-PERMISSION")
    DIAGNOSTIC___ACCESS___PERMISSION("DIAGNOSTIC-ACCESS-PERMISSION"),
    @XmlEnumValue("DIAGNOSTIC-AGING")
    DIAGNOSTIC___AGING("DIAGNOSTIC-AGING"),
    @XmlEnumValue("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION")
    DIAGNOSTIC___CLEAR___DIAGNOSTIC___INFORMATION("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION"),
    @XmlEnumValue("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS")
    DIAGNOSTIC___CLEAR___DIAGNOSTIC___INFORMATION___CLASS("DIAGNOSTIC-CLEAR-DIAGNOSTIC-INFORMATION-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-COM-CONTROL")
    DIAGNOSTIC___COM___CONTROL("DIAGNOSTIC-COM-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-COM-CONTROL-CLASS")
    DIAGNOSTIC___COM___CONTROL___CLASS("DIAGNOSTIC-COM-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-COMMON-ELEMENT")
    DIAGNOSTIC___COMMON___ELEMENT("DIAGNOSTIC-COMMON-ELEMENT"),
    @XmlEnumValue("DIAGNOSTIC-CONDITION")
    DIAGNOSTIC___CONDITION("DIAGNOSTIC-CONDITION"),
    @XmlEnumValue("DIAGNOSTIC-CONDITION-GROUP")
    DIAGNOSTIC___CONDITION___GROUP("DIAGNOSTIC-CONDITION-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-CONTROL-DTC-SETTING")
    DIAGNOSTIC___CONTROL___DTC___SETTING("DIAGNOSTIC-CONTROL-DTC-SETTING"),
    @XmlEnumValue("DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS")
    DIAGNOSTIC___CONTROL___DTC___SETTING___CLASS("DIAGNOSTIC-CONTROL-DTC-SETTING-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-CUSTOM-SERVICE-CLASS")
    DIAGNOSTIC___CUSTOM___SERVICE___CLASS("DIAGNOSTIC-CUSTOM-SERVICE-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___DATA___BY___IDENTIFIER("DIAGNOSTIC-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-IDENTIFIER")
    DIAGNOSTIC___DATA___IDENTIFIER("DIAGNOSTIC-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-IDENTIFIER-SET")
    DIAGNOSTIC___DATA___IDENTIFIER___SET("DIAGNOSTIC-DATA-IDENTIFIER-SET"),
    @XmlEnumValue("DIAGNOSTIC-DATA-TRANSFER")
    DIAGNOSTIC___DATA___TRANSFER("DIAGNOSTIC-DATA-TRANSFER"),
    @XmlEnumValue("DIAGNOSTIC-DATA-TRANSFER-CLASS")
    DIAGNOSTIC___DATA___TRANSFER___CLASS("DIAGNOSTIC-DATA-TRANSFER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING")
    DIAGNOSTIC___DEM___PROVIDED___DATA___MAPPING("DIAGNOSTIC-DEM-PROVIDED-DATA-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER")
    DIAGNOSTIC___DYNAMIC___DATA___IDENTIFIER("DIAGNOSTIC-DYNAMIC-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER")
    DIAGNOSTIC___DYNAMICALLY___DEFINE___DATA___IDENTIFIER("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS")
    DIAGNOSTIC___DYNAMICALLY___DEFINE___DATA___IDENTIFIER___CLASS("DIAGNOSTIC-DYNAMICALLY-DEFINE-DATA-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ECU-RESET")
    DIAGNOSTIC___ECU___RESET("DIAGNOSTIC-ECU-RESET"),
    @XmlEnumValue("DIAGNOSTIC-ECU-RESET-CLASS")
    DIAGNOSTIC___ECU___RESET___CLASS("DIAGNOSTIC-ECU-RESET-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ENABLE-CONDITION")
    DIAGNOSTIC___ENABLE___CONDITION("DIAGNOSTIC-ENABLE-CONDITION"),
    @XmlEnumValue("DIAGNOSTIC-ENABLE-CONDITION-GROUP")
    DIAGNOSTIC___ENABLE___CONDITION___GROUP("DIAGNOSTIC-ENABLE-CONDITION-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING")
    DIAGNOSTIC___ENABLE___CONDITION___PORT___MAPPING("DIAGNOSTIC-ENABLE-CONDITION-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT")
    DIAGNOSTIC___EVENT("DIAGNOSTIC-EVENT"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-PORT-MAPPING")
    DIAGNOSTIC___EVENT___PORT___MAPPING("DIAGNOSTIC-EVENT-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING")
    DIAGNOSTIC___EVENT___TO___DEBOUNCE___ALGORITHM___MAPPING("DIAGNOSTIC-EVENT-TO-DEBOUNCE-ALGORITHM-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING")
    DIAGNOSTIC___EVENT___TO___ENABLE___CONDITION___GROUP___MAPPING("DIAGNOSTIC-EVENT-TO-ENABLE-CONDITION-GROUP-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING")
    DIAGNOSTIC___EVENT___TO___OPERATION___CYCLE___MAPPING("DIAGNOSTIC-EVENT-TO-OPERATION-CYCLE-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING")
    DIAGNOSTIC___EVENT___TO___STORAGE___CONDITION___GROUP___MAPPING("DIAGNOSTIC-EVENT-TO-STORAGE-CONDITION-GROUP-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING")
    DIAGNOSTIC___EVENT___TO___TROUBLE___CODE___UDS___MAPPING("DIAGNOSTIC-EVENT-TO-TROUBLE-CODE-UDS-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-EXTENDED-DATA-RECORD")
    DIAGNOSTIC___EXTENDED___DATA___RECORD("DIAGNOSTIC-EXTENDED-DATA-RECORD"),
    @XmlEnumValue("DIAGNOSTIC-FREEZE-FRAME")
    DIAGNOSTIC___FREEZE___FRAME("DIAGNOSTIC-FREEZE-FRAME"),
    @XmlEnumValue("DIAGNOSTIC-IO-CONTROL")
    DIAGNOSTIC___IO___CONTROL("DIAGNOSTIC-IO-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-INDICATOR")
    DIAGNOSTIC___INDICATOR("DIAGNOSTIC-INDICATOR"),
    @XmlEnumValue("DIAGNOSTIC-IO-CONTROL-CLASS")
    DIAGNOSTIC___IO___CONTROL___CLASS("DIAGNOSTIC-IO-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-MAPPING")
    DIAGNOSTIC___MAPPING("DIAGNOSTIC-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS")
    DIAGNOSTIC___MEMORY___ADDRESSABLE___RANGE___ACCESS("DIAGNOSTIC-MEMORY-ADDRESSABLE-RANGE-ACCESS"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___MEMORY___BY___ADDRESS("DIAGNOSTIC-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION")
    DIAGNOSTIC___MEMORY___DESTINATION("DIAGNOSTIC-MEMORY-DESTINATION"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION-MIRROR")
    DIAGNOSTIC___MEMORY___DESTINATION___MIRROR("DIAGNOSTIC-MEMORY-DESTINATION-MIRROR"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY")
    DIAGNOSTIC___MEMORY___DESTINATION___PRIMARY("DIAGNOSTIC-MEMORY-DESTINATION-PRIMARY"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED")
    DIAGNOSTIC___MEMORY___DESTINATION___USER___DEFINED("DIAGNOSTIC-MEMORY-DESTINATION-USER-DEFINED"),
    @XmlEnumValue("DIAGNOSTIC-MEMORY-IDENTIFIER")
    DIAGNOSTIC___MEMORY___IDENTIFIER("DIAGNOSTIC-MEMORY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-OPERATION-CYCLE")
    DIAGNOSTIC___OPERATION___CYCLE("DIAGNOSTIC-OPERATION-CYCLE"),
    @XmlEnumValue("DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING")
    DIAGNOSTIC___OPERATION___CYCLE___PORT___MAPPING("DIAGNOSTIC-OPERATION-CYCLE-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-READ-DTC-INFORMATION")
    DIAGNOSTIC___READ___DTC___INFORMATION("DIAGNOSTIC-READ-DTC-INFORMATION"),
    @XmlEnumValue("DIAGNOSTIC-READ-DTC-INFORMATION-CLASS")
    DIAGNOSTIC___READ___DTC___INFORMATION___CLASS("DIAGNOSTIC-READ-DTC-INFORMATION-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___READ___DATA___BY___IDENTIFIER("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS")
    DIAGNOSTIC___READ___DATA___BY___IDENTIFIER___CLASS("DIAGNOSTIC-READ-DATA-BY-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID")
    DIAGNOSTIC___READ___DATA___BY___PERIODIC___ID("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID"),
    @XmlEnumValue("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS")
    DIAGNOSTIC___READ___DATA___BY___PERIODIC___ID___CLASS("DIAGNOSTIC-READ-DATA-BY-PERIODIC-ID-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___READ___MEMORY___BY___ADDRESS("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS")
    DIAGNOSTIC___READ___MEMORY___BY___ADDRESS___CLASS("DIAGNOSTIC-READ-MEMORY-BY-ADDRESS-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-DOWNLOAD")
    DIAGNOSTIC___REQUEST___DOWNLOAD("DIAGNOSTIC-REQUEST-DOWNLOAD"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS")
    DIAGNOSTIC___REQUEST___DOWNLOAD___CLASS("DIAGNOSTIC-REQUEST-DOWNLOAD-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-FILE-TRANSFER")
    DIAGNOSTIC___REQUEST___FILE___TRANSFER("DIAGNOSTIC-REQUEST-FILE-TRANSFER"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS")
    DIAGNOSTIC___REQUEST___FILE___TRANSFER___CLASS("DIAGNOSTIC-REQUEST-FILE-TRANSFER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-UPLOAD")
    DIAGNOSTIC___REQUEST___UPLOAD("DIAGNOSTIC-REQUEST-UPLOAD"),
    @XmlEnumValue("DIAGNOSTIC-REQUEST-UPLOAD-CLASS")
    DIAGNOSTIC___REQUEST___UPLOAD___CLASS("DIAGNOSTIC-REQUEST-UPLOAD-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-RESPONSE-ON-EVENT")
    DIAGNOSTIC___RESPONSE___ON___EVENT("DIAGNOSTIC-RESPONSE-ON-EVENT"),
    @XmlEnumValue("DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS")
    DIAGNOSTIC___RESPONSE___ON___EVENT___CLASS("DIAGNOSTIC-RESPONSE-ON-EVENT-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE")
    DIAGNOSTIC___ROUTINE("DIAGNOSTIC-ROUTINE"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE-CONTROL")
    DIAGNOSTIC___ROUTINE___CONTROL("DIAGNOSTIC-ROUTINE-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-ROUTINE-CONTROL-CLASS")
    DIAGNOSTIC___ROUTINE___CONTROL___CLASS("DIAGNOSTIC-ROUTINE-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-ACCESS")
    DIAGNOSTIC___SECURITY___ACCESS("DIAGNOSTIC-SECURITY-ACCESS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-ACCESS-CLASS")
    DIAGNOSTIC___SECURITY___ACCESS___CLASS("DIAGNOSTIC-SECURITY-ACCESS-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SECURITY-LEVEL")
    DIAGNOSTIC___SECURITY___LEVEL("DIAGNOSTIC-SECURITY-LEVEL"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-CLASS")
    DIAGNOSTIC___SERVICE___CLASS("DIAGNOSTIC-SERVICE-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-DATA-MAPPING")
    DIAGNOSTIC___SERVICE___DATA___MAPPING("DIAGNOSTIC-SERVICE-DATA-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-INSTANCE")
    DIAGNOSTIC___SERVICE___INSTANCE("DIAGNOSTIC-SERVICE-INSTANCE"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-SW-MAPPING")
    DIAGNOSTIC___SERVICE___SW___MAPPING("DIAGNOSTIC-SERVICE-SW-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-SERVICE-TABLE")
    DIAGNOSTIC___SERVICE___TABLE("DIAGNOSTIC-SERVICE-TABLE"),
    @XmlEnumValue("DIAGNOSTIC-SESSION")
    DIAGNOSTIC___SESSION("DIAGNOSTIC-SESSION"),
    @XmlEnumValue("DIAGNOSTIC-SESSION-CONTROL")
    DIAGNOSTIC___SESSION___CONTROL("DIAGNOSTIC-SESSION-CONTROL"),
    @XmlEnumValue("DIAGNOSTIC-SESSION-CONTROL-CLASS")
    DIAGNOSTIC___SESSION___CONTROL___CLASS("DIAGNOSTIC-SESSION-CONTROL-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-STORAGE-CONDITION")
    DIAGNOSTIC___STORAGE___CONDITION("DIAGNOSTIC-STORAGE-CONDITION"),
    @XmlEnumValue("DIAGNOSTIC-STORAGE-CONDITION-GROUP")
    DIAGNOSTIC___STORAGE___CONDITION___GROUP("DIAGNOSTIC-STORAGE-CONDITION-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING")
    DIAGNOSTIC___STORAGE___CONDITION___PORT___MAPPING("DIAGNOSTIC-STORAGE-CONDITION-PORT-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-SW-MAPPING")
    DIAGNOSTIC___SW___MAPPING("DIAGNOSTIC-SW-MAPPING"),
    @XmlEnumValue("DIAGNOSTIC-TRANSFER-EXIT")
    DIAGNOSTIC___TRANSFER___EXIT("DIAGNOSTIC-TRANSFER-EXIT"),
    @XmlEnumValue("DIAGNOSTIC-TRANSFER-EXIT-CLASS")
    DIAGNOSTIC___TRANSFER___EXIT___CLASS("DIAGNOSTIC-TRANSFER-EXIT-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE")
    DIAGNOSTIC___TROUBLE___CODE("DIAGNOSTIC-TROUBLE-CODE"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-GROUP")
    DIAGNOSTIC___TROUBLE___CODE___GROUP("DIAGNOSTIC-TROUBLE-CODE-GROUP"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-J-1939")
    DIAGNOSTIC___TROUBLE___CODE___J___1939("DIAGNOSTIC-TROUBLE-CODE-J-1939"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-OBD")
    DIAGNOSTIC___TROUBLE___CODE___OBD("DIAGNOSTIC-TROUBLE-CODE-OBD"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-PROPS")
    DIAGNOSTIC___TROUBLE___CODE___PROPS("DIAGNOSTIC-TROUBLE-CODE-PROPS"),
    @XmlEnumValue("DIAGNOSTIC-TROUBLE-CODE-UDS")
    DIAGNOSTIC___TROUBLE___CODE___UDS("DIAGNOSTIC-TROUBLE-CODE-UDS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER")
    DIAGNOSTIC___WRITE___DATA___BY___IDENTIFIER("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS")
    DIAGNOSTIC___WRITE___DATA___BY___IDENTIFIER___CLASS("DIAGNOSTIC-WRITE-DATA-BY-IDENTIFIER-CLASS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS")
    DIAGNOSTIC___WRITE___MEMORY___BY___ADDRESS("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS"),
    @XmlEnumValue("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS")
    DIAGNOSTIC___WRITE___MEMORY___BY___ADDRESS___CLASS("DIAGNOSTIC-WRITE-MEMORY-BY-ADDRESS-CLASS");
    private final String value;

    DIAGNOSTICCOMMONELEMENTSUBTYPESENUM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DIAGNOSTICCOMMONELEMENTSUBTYPESENUM fromValue(String v) {
        for (DIAGNOSTICCOMMONELEMENTSUBTYPESENUM c: DIAGNOSTICCOMMONELEMENTSUBTYPESENUM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
